include $(TOPDIR)/rules.mk

PROFILE_DESCRIPTION:=Gateway with VPN for remote connection to wifi mesh testing network in Canodrom @Barcelona
PROFILE_DEPENDS:= +wireguard-tools

include ../../profile.mk

# call BuildPackage - OpenWrt buildroot signature
