#!/bin/sh
##Lo primero que hacemos es agregar el gateway de la lan de forma manual
##Este gateway es el PfSense que tenemos en la red
uci set network.lan.gateway='10.17.95.1'
###Lo segundo es modificar un par de opciones en el servidor DHCP (DNSmasq) de cada uno de los nodos
##Para que los clientes seban que maquina es la salida a internet
###Tambien agregamos reglas al dns para definir nuestro  dominio local
uci add_list dhcp.@dnsmasq[0].dhcp_option='3,10.17.95.1'
uci add_list dhcp.@dnsmasq[0].dhcp_option='121,10.17.0.0/16,10.17.0.1'
uci add_list dhcp.@dnsmasq[0].dhcp_option='249,10.17.0.0/16,10.17.0.1'
uci add_list dhcp.@dnsmasq[0].address='/.redcomani.org/10.17.95.2'
uci add_list dhcp.@dnsmasq[0].address='/firewall.redcomani.org/10.17.95.1'
uci add_list dhcp.@dnsmasq[0].address='/pve.redcomani.org/10.17.95.3'
uci add_list dhcp.@dnsmasq[0].address='/unms.redcomani.org/10.17.95.4'
