#!/bin/sh

#location="$(uci -q get lime.system.location || uci -q get lime-defaults.system.location)"
#contact="$(uci -q get lime.system.contact || uci -q get lime-defaults.system.contact)"

#uci delete snmpd.@system[0].sysName
#uci set snmpd.@system[0].sysLocation="$location"
#uci set snmpd.@system[0].sysContact="$contact"
#uci set snmpd.@agent[0].agentaddress='UDP:161,UDP6:161'
#uci set snmpd.public6=com2sec6
#uci set snmpd.public6.secname=ro
#uci set snmpd.public6.source=default
#uci set snmpd.public6.community=public
#uci commit snmpd
