include $(TOPDIR)/rules.mk

PROFILE_DESCRIPTION:=Prometheus collectors and script to push to a pushgateway server
PROFILE_DEPENDS:=+prometheus-node-exporter-lua

include ../../profile.mk

# call BuildPackage - OpenWrt buildroot signature
