#!/bin/sh

uci set prometheus-node-exporter-lua.main.listen_interface=lan
uci set prometheus-node-exporter-lua.main.listen_ipv6=0
uci set prometheus-node-exporter-lua.main.listen_port=9090
uci commit prometheus-node-exporter-lua

[ -x /etc/init.d/prometheus-node-exporter-lua ] &&
	/etc/init.d/prometheus-node-exporter-lua enable
exit 0
