#!/bin/sh

# Si anda llegar a la praviana extendemos el plazo de "deferable reboot".
# Es el último recurso para no quedar desconectados del nodo si queda en un estado inaccesible.

internet_gw_ip=10.5.40.2

unique_append()
{
	grep -qF "$1" "$2" || echo "$1" >> "$2"
}

unique_append \
	"*/10 * * * * ((if ping -c 10 -W 10 $internet_gw_ip &> /dev/null; then awk '{print \$1 + 800}' /proc/uptime > /tmp/deferable-reboot.defer ; fi )&) "\
	/etc/crontabs/root