include $(TOPDIR)/rules.mk

PROFILE_DESCRIPTION:=Use 802.11s for mesh and WPA3 encryption
PROFILE_DEPENDS:=+wpad-mesh-openssl

include ../../profile.mk

# call BuildPackage - OpenWrt buildroot signature
