#!/bin/sh

# LibreRouter V1 Prototypes come with a fake MAC on all radios.
# Generate 4 random bytes on first boot, and assign arbitrary macaddr
# to all radios, prepending 02:, and appending a unique index

rand4bytes=$(head -c 256 /dev/urandom | md5sum | sed 's/\(..\)/\1:/g' | head -c 11)

for index in 0 1 2; do
    uci delete lime.radio$index
    uci commit lime

    sed -i '/^config lime .wifi./{ :x ; H; n; /^$/{x;s/config lime .wifi./config wifi '"'radio$index'"'/;p;x} ; /^$/b ; bx ; }' /etc/config/lime
    
    uci set lime.radio$index.ieee80211s_macaddr="02:$rand4bytes":0$index
    uci set lime.radio$index.adhoc_macaddr="02:$rand4bytes":1$index
    uci set lime.radio$index.ap_macaddr="02:$rand4bytes":2$index
    uci set lime.radio$index.apname_macaddr="02:$rand4bytes":3$index
    uci commit lime
done

