include $(TOPDIR)/rules.mk

PROFILE_DESCRIPTION:=Use 802.11s with SAE for mesh, route with bmx7 and batman-adv
PROFILE_DEPENDS:=+wpad-mesh-wolfssl +wpa-cli +kmod-batman-adv +bmx7 +bmx7-iwinfo +bmx7-json +bmx7-sms +bmx7-table +bmx7-tun +bmx7-uci-config +lime-proto-batadv +bmx7-auto-gw-mode +lime-proto-bmx7 +lime-proto-anygw +uhttpd-mod-lua +shared-state +shared-state-dnsmasq_hosts +shared-state-dnsmasq_leases +shared-state-bat_hosts +wifi-unstuck-wa

include ../../profile.mk

# call BuildPackage - OpenWrt buildroot signature
