include $(TOPDIR)/rules.mk

PROFILE_DESCRIPTION:=Simple profile for experimenting with mesh networks at Canodrom in Barcelona

include ../../profile.mk

# call BuildPackage - OpenWrt buildroot signature
