name: Build network profiles

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: aparcar/action-openwrt-sdk@master
        env:
          EXTRA_FEEDS: "src-git|libremesh|https://github.com/libremesh/lime-packages.git"

      - name: Upload
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: libremesh
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: https://images.aparcar.org
          SOURCE_DIR: bin/packages/x86_64/action/
          DEST_DIR: profiles/

